warning: in the working copy of '.github/workflows/quality.yml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/interface-verification-path.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/icons/cadence/ajouter.svg', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'public/service-worker.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/App.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/actions/campaignActions.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/components/ErrorBoundary.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/constants.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/hooks/useCampaign.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/i18n/translations-random.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/i18n/translations.csv', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/app/AdminPresetsPage.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/app/MenuOptions.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/app/appSupport.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/campaign/HubCampagne.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/campaign/TemplatePersonnageList.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/dialogues/FenetreLancerDes.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/dialogues/FenetreLancerDes.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/dialogues/FenetreLancerDes.test.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/dialogues/FenetreLancerInitiatives.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/dialogues/FenetreLancerInitiatives.test.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/fiches/FenetreEditionFiche.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/fiches/FicheParticipant.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/icones/IconeCadence.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/interface/icones/IconesCadence.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/localCampaignStorage.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/logic.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/core/definitions.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/definitionAccess.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/definitionAccess.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/definitionCompiler.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/definitionDraft.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/randomStatistics.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/rollCode.tests/part-1.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/rulePresetKits.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/rulePresetKits.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/state.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/state.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/storage.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/styles/base.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/styles/configuration-kits-sources.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/styles/configuration.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/ConfigurationPanel.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/HistoryPanel.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/RandomKitManager.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/RandomSystemUi.tests/part-1.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/ResultView.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/SourceManager.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/StatisticsPanel.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/UsePanel.jsx', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/ui/sourceManagerDraft.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/useRandomSystem.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/random-system/useRandomSystem.test.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/storage.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles/refinements/hub.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles/refinements/participants.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles/refinements/shell.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles/theme/dark-compatibility.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/template-hub.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tests/uiux/full-uiux-routine.mjs', LF will be replaced by CRLF the next time Git touches it
