import { t } from '../../i18n/index.js';
import { randomSourceKinds } from '../engine.js';
import { createResourceId } from '../resourceIds.js';

export const CSV_EXAMPLE = 'plage,nom,symbole,texte\n1-2,Soleil,,Ciel bien degage\n3,Nuage,,Quelques nuages\n4,Pluie,,Averses possibles';
const MAX_GUIDED_UNIFORM_FACES = 200;

export function weightedRow(outcome = {}, index = 0) { return { id: outcome.id || createResourceId('outcome'), label: outcome.label || '', weight: outcome.weight ?? 1, value: outcome.value ?? '', symbol: outcome.symbol || '', image: outcome.image || '', text: outcome.text || '', index }; }
export function cardRow(card = {}, index = 0) { return { id: card.id || `card-${index + 1}`, label: card.label || '', value: card.value ?? card.label ?? '', rank: card.rank || '', suit: card.suit || '', color: card.color || '', symbol: card.symbol || '', image: card.image || '', text: card.comment || '', markers: card.markers || [] }; }
export function listedEntries(value) { return String(value || '').split(/\r?\n/).map((label, lineIndex) => ({ label: label.trim(), lineIndex })).filter((entry) => entry.label); }
export function cleanDetailMap(enabled, details) { return enabled ? Object.fromEntries(Object.entries(details).map(([value, detail]) => [value, String(detail || '').trim()]).filter(([, detail]) => detail)) : {}; }
export function uniformFaceValues(draft) { const min = Number(draft.min); const max = Number(draft.max); const step = Math.abs(Number(draft.step)); if (!Number.isFinite(min) || !Number.isFinite(max) || !Number.isFinite(step) || step <= 0 || max < min) return []; const count = Math.floor((max - min) / step) + 1; if (count > MAX_GUIDED_UNIFORM_FACES) return null; return Array.from({ length: Math.max(1, count) }, (_, index) => { const raw = min + (index * step); return Number.isInteger(raw) ? raw : Number(raw.toFixed(10)); }); }
export function sourceToCsv(source) { if (source?.kind !== randomSourceKinds.WEIGHTED) return CSV_EXAMPLE; const escape = (value) => { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }; return ['nom,poids,valeur,symbole,image,texte', ...source.outcomes.map((outcome) => [escape(outcome.label), outcome.weight, escape(outcome.value), escape(outcome.symbol), escape(outcome.image), escape(outcome.text)].join(','))].join('\n'); }
export function sourceUsedByDefinitions(sourceId, definitions) { return definitions.some((definition) => definition.components.some((component) => component.source.kind === 'fixed' && component.source.value === sourceId) || definition.parameters.some((parameter) => parameter.type === 'source' && parameter.defaultValue === sourceId) || definition.pipeline?.some((step) => step.type === 'lookup-table' && step.sourceId === sourceId)); }
export function sourceKindLabel(source) { if (source.note) return source.note; if (source.kind === randomSourceKinds.CARDS) return t('random.source.cards'); if (source.kind === randomSourceKinds.WEIGHTED) return t('random.source.weighted'); return t('random.source.uniform'); }
export function sourceDraft(source, definitions = []) { if (!source) return { id: createResourceId('source'), name: 'Nouvelle source', note: '', kind: randomSourceKinds.UNIFORM, min: 1, max: 6, step: 1, describeFaces: false, faceLabels: {}, faceSymbols: {}, faceImages: {}, faceTexts: {}, weightedMode: 'guided', outcomes: [weightedRow()], weightedEntries: '', csv: CSV_EXAMPLE, cards: '', cardDetails: [], createSimpleRoll: false }; return { id: source.id, name: source.name, note: source.note || '', kind: source.kind, min: source.min ?? 1, max: source.max ?? 6, step: source.step ?? 1, describeFaces: source.kind === randomSourceKinds.UNIFORM && [source.labels, source.symbols, source.images, source.texts].some((details) => Object.keys(details || {}).length > 0), faceLabels: source.labels || {}, faceSymbols: source.symbols || {}, faceImages: source.images || {}, faceTexts: source.texts || {}, weightedMode: 'guided', outcomes: source.kind === randomSourceKinds.WEIGHTED ? source.outcomes.map(weightedRow) : [weightedRow()], weightedEntries: source.kind === randomSourceKinds.WEIGHTED ? source.outcomes.map((outcome) => outcome.label).join('\n') : '', csv: sourceToCsv(source), cards: source.kind === randomSourceKinds.CARDS ? source.cards.map((card) => card.label).join('\n') : '', cardDetails: source.kind === randomSourceKinds.CARDS ? source.cards.map(cardRow) : [], createSimpleRoll: definitions.some((definition) => definition?.sourceId === source.id) }; }
export function uniformDetailOptions(faceValues) { return Array.isArray(faceValues) ? faceValues.map((value) => ({ value: String(value), label: String(value) })) : []; }
export function ensureSelection(options, current) { return options.length ? (options.some((option) => option.value === current) ? current : options[0].value) : ''; }
export function selectedEntryIndex(entries, selectedLine) { if (!entries.length) return -1; const index = entries.findIndex((entry) => String(entry.lineIndex) === selectedLine); return index >= 0 ? index : 0; }
