import { useState } from 'react';
import { colorNames, participantKinds, trackerTypeLabels } from '../constants.js';
import { clone, colors, isVisible, newTracker, symbols } from '../logic.js';
import { Sheet } from './common.jsx';

function TrackerEditor({ tracker, onChange, onDelete }) {
  const patch = (value) => onChange({ ...tracker, ...value });

  return <div className="tracker"><div className="row"><input value={tracker.name} onChange={(e) => patch({ name: e.target.value })} style={{ flex:1 }} /><button className="danger-btn" onClick={onDelete}>×</button></div><div className="grid2"><label className="field">Type<select value={tracker.type} onChange={(e) => onChange({ ...newTracker(e.target.value), id: tracker.id, name: tracker.name })}>{Object.entries(trackerTypeLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{tracker.type !== 'boxes' && <label className="field">Valeur<input type="number" value={tracker.current ?? 0} onChange={(e) => patch({ current: Number(e.target.value) })} /></label>}{tracker.type !== 'number' && tracker.type !== 'boxes' && <label className="field">Maximum<input type="number" value={tracker.max ?? 1} onChange={(e) => patch({ max: Math.max(1, Number(e.target.value)) })} /></label>}{(tracker.type === 'bar' || tracker.type === 'number') && <label className="field">Minimum<input type="number" value={tracker.min ?? 0} onChange={(e) => patch({ min: Number(e.target.value) })} /></label>}{(tracker.type === 'bar' || tracker.type === 'number') && <label className="field">Pas<input type="number" value={tracker.step ?? 1} onChange={(e) => patch({ step: Math.max(1, Number(e.target.value)) })} /></label>}</div><label className="row"><input type="checkbox" checked={isVisible(tracker)} onChange={(e) => patch({ visible: e.target.checked })} /> visible sur fichette</label>{tracker.type === 'bar' && <div className="grid2"><label className="row"><input type="checkbox" checked={!!tracker.minAbsolute} onChange={(e) => patch({ minAbsolute: e.target.checked })} /> min absolu</label><label className="row"><input type="checkbox" checked={!!tracker.maxAbsolute} onChange={(e) => patch({ maxAbsolute: e.target.checked })} /> max absolu</label></div>}{tracker.type === 'clock' && <label className="row"><input type="checkbox" checked={!!tracker.auto} onChange={(e) => patch({ auto: e.target.checked })} /> avance automatique</label>}</div>;
}

export function EditSheet({ participant, onClose, onSave, onDelete }) {
  const [draft, setDraft] = useState(clone(participant));
  const patch = (key, value) => setDraft((d) => ({ ...d, [key]: value }));
  const updateTracker = (id, next) => setDraft((d) => ({ ...d, trackers: d.trackers.map((t) => t.id === id ? next : t) }));

  return <Sheet title="Modifier" onClose={onClose}><label className="field">Nom<input value={draft.name} onChange={(e) => patch('name', e.target.value)} /></label><label className="field">Description<textarea value={draft.description || ''} onChange={(e) => patch('description', e.target.value)} /></label><div className="grid2"><label className="field">Type<select value={draft.kind} onChange={(e) => patch('kind', e.target.value)}>{participantKinds.map((k) => <option key={k}>{k}</option>)}</select></label><label className="field">Initiative<input type="number" value={draft.initiative} onChange={(e) => patch('initiative', Number(e.target.value))} /></label></div><label className="field">Symbole<div className="statuses">{symbols.map((s) => <button key={s} className="small-btn" onClick={() => patch('symbol', s)}>{s}</button>)}</div></label><label className="field">Couleur<div className="statuses">{colors.map((c) => <button key={c} className="small-btn" onClick={() => patch('color', c)}>{colorNames[c] || c}</button>)}</div></label><h3>Suivis</h3><div className="stack">{draft.trackers.map((tracker) => <TrackerEditor key={tracker.id} tracker={tracker} onChange={(next) => updateTracker(tracker.id, next)} onDelete={() => setDraft((d) => ({ ...d, trackers: d.trackers.filter((t) => t.id !== tracker.id) }))} />)}<button className="primary" onClick={() => setDraft((d) => ({ ...d, trackers: [...d.trackers, newTracker('bar')] }))}>Ajouter un suivi</button></div><div className="grid2" style={{ marginTop: 12 }}><button className="primary" onClick={() => onSave(draft)}>Valider</button><button className="danger-btn" onClick={onDelete}>Supprimer la fiche</button></div></Sheet>;
}
