import { useState } from 'react';
import { APP_VERSION } from '../constants.js';
import { Sheet } from './common.jsx';

function GlobalTrackerOptions({ tracker, onChange }) {
  const current = tracker || { enabled: false, name: 'Menace', mode: 'counter', current: 0, max: 6, auto: false };
  const patch = (value) => onChange({ ...current, ...value });

  return <div className="scene-options"><h3>Compteur de scène</h3><label className="row"><input type="checkbox" checked={!!current.enabled} onChange={(e) => patch({ enabled: e.target.checked })} /> afficher dans l’en-tête</label>{current.enabled && <div className="stack"><label className="field">Nom<input value={current.name || ''} onChange={(e) => patch({ name: e.target.value })} placeholder="Menace" /></label><div className="grid2"><label className="field">Type<select value={current.mode || 'counter'} onChange={(e) => patch({ mode: e.target.value })}><option value="counter">Compteur</option><option value="clock">Horloge</option></select></label><label className="field">Valeur<input type="number" inputMode="numeric" value={current.current ?? 0} onChange={(e) => patch({ current: e.target.value === '' ? 0 : Number(e.target.value) })} /></label></div>{current.mode === 'clock' && <label className="field">Maximum<input type="number" inputMode="numeric" min="1" value={current.max ?? 6} onChange={(e) => patch({ max: Math.max(1, Number(e.target.value) || 1) })} /></label>}<label className="row"><input type="checkbox" checked={!!current.auto} onChange={(e) => patch({ auto: e.target.checked })} /> avance à chaque nouveau round</label></div>}</div>;
}

export function Menu({ scenes, scene, restorePoints = [], onRestore, onClose, setSceneIndex, dark, setDark, onAddParticipant, onNewScene, onExport, onImport, onReset, onGlobalTracker }) {
  const orderedRestorePoints = [...restorePoints].sort((a, b) => a.round - b.round);
  const [restoreId, setRestoreId] = useState(orderedRestorePoints.at(-1)?.id || '');

  return <Sheet title="Menu" onClose={onClose}><div className="menu-topline"><span className="version-chip">v{APP_VERSION}</span><button className={`theme-toggle ${dark ? 'dark-on' : 'light-on'}`} onClick={() => setDark(!dark)} aria-label="Basculer thème clair ou sombre"><span>☀</span><span>☾</span><i /></button></div><h3>Scènes</h3><div className="stack">{scenes.map((s, i) => <button className="small-btn" key={s.id} onClick={() => { setSceneIndex(i); onClose(); }}>{s.title} · R{s.round}</button>)}</div><GlobalTrackerOptions tracker={scene?.globalTracker} onChange={onGlobalTracker} /><div className="stack" style={{ marginTop: 12 }}><button className="primary" onClick={onAddParticipant}>Ajouter un personnage</button><button className="small-btn" onClick={onNewScene}>Nouvelle scène</button></div><h3>Sauvegarde</h3><div className="grid2"><button className="primary" onClick={onExport}>Exporter</button><label className="small-btn" style={{ textAlign:'center' }}>Importer<input type="file" accept=".json,application/json" style={{ display:'none' }} onChange={(e) => e.target.files?.[0] && onImport(e.target.files[0])} /></label></div><button className="danger-btn" style={{ marginTop: 8, width:'100%' }} onClick={onReset}>Réinitialiser la démo</button>{orderedRestorePoints.length > 0 && <div className="restore-row discreet"><label>Restaurer</label><select value={restoreId} onChange={(e) => setRestoreId(e.target.value)}>{orderedRestorePoints.map((point) => <option key={point.id} value={point.id}>{point.title}</option>)}</select><button className="small-btn" disabled={!restoreId} onClick={() => onRestore(restoreId)}>OK</button></div>}</Sheet>;
}
