import { useState } from 'react';
import { Sheet } from './common.jsx';

export function Menu({ scenes, restorePoints = [], onRestore, onClose, setSceneIndex, dark, setDark, onAddParticipant, onNewScene, onExport, onImport, onReset }) {
  const orderedRestorePoints = [...restorePoints].sort((a, b) => a.round - b.round);
  const [restoreId, setRestoreId] = useState(orderedRestorePoints.at(-1)?.id || '');

  return <Sheet title="Menu" onClose={onClose}><div className="menu-theme"><button className={`theme-toggle ${dark ? 'dark-on' : 'light-on'}`} onClick={() => setDark(!dark)} aria-label="Basculer thème clair ou sombre"><span>☀</span><span>☾</span><i /></button></div><h3>Scènes</h3><div className="stack">{scenes.map((s, i) => <button className="small-btn" key={s.id} onClick={() => { setSceneIndex(i); onClose(); }}>{s.title} · R{s.round}</button>)}</div>{orderedRestorePoints.length > 0 && <div className="restore-row"><label>Restaurer</label><select value={restoreId} onChange={(e) => setRestoreId(e.target.value)}>{orderedRestorePoints.map((point) => <option key={point.id} value={point.id}>{point.title}</option>)}</select><button className="small-btn" disabled={!restoreId} onClick={() => onRestore(restoreId)}>↩</button></div>}<div className="stack" style={{ marginTop: 12 }}><button className="primary" onClick={onAddParticipant}>Ajouter un personnage</button><button className="small-btn" onClick={onNewScene}>Nouvelle scène</button></div><h3>Sauvegarde</h3><div className="grid2"><button className="primary" onClick={onExport}>Exporter</button><label className="small-btn" style={{ textAlign:'center' }}>Importer<input type="file" accept=".json,application/json" style={{ display:'none' }} onChange={(e) => e.target.files?.[0] && onImport(e.target.files[0])} /></label></div><button className="danger-btn" style={{ marginTop: 8, width:'100%' }} onClick={onReset}>Réinitialiser la démo</button></Sheet>;
}
